import test from 'node:test'
import assert from 'node:assert/strict'
import { mkdtemp, mkdir, writeFile, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { get } from 'node:http'
import { startDiscoverFixture } from './serve-discover-fixture.mjs'

test('local Discover fixture serves real assets with a warning and read-only deterministic APIs', async (t) => {
  const root = await mkdtemp(join(tmpdir(), 'discover-fixture-test-'))
  await mkdir(join(root, 'depot'))
  await writeFile(join(root, 'depot/index.html'), '<html><head></head><body>Actual export fixture</body></html>')
  await writeFile(join(root, 'depot/index.txt'), 'RSC fixture')
  await writeFile(join(root, 'depot/__next._full.txt'), 'Segment fixture')
  const requests = []
  const { server, url } = await startDiscoverFixture({ root, port: 0, onRequest: (entry) => requests.push(entry) })
  t.after(async () => { await new Promise((done) => server.close(done)); await rm(root, { recursive: true }) })
  assert.equal(server.address().address, '127.0.0.1')
  const html = await fetch(`${url}/depot/`)
  assert.match(await html.text(), /Fixture data — not production/)
  assert.match(html.headers.get('content-security-policy'), /connect-src 'self'/)
  const mobile = await fetch(`${url}/_fixture/mobile`)
  assert.equal(mobile.status, 200)
  assert.match(mobile.headers.get('content-security-policy'), /frame-src 'self'/)
  assert.match(await mobile.text(), /width:390px;height:844px.*title="Discover at phone width" src="\/depot\/"/)
  const mobileLibrary = await fetch(`${url}/_fixture/mobile/library`)
  assert.equal(mobileLibrary.status, 200)
  assert.match(await mobileLibrary.text(), /title="Library at phone width" src="\/library\/"/)
  const mobileGateway = await fetch(`${url}/_fixture/mobile/gateways`)
  assert.equal(mobileGateway.status, 200)
  assert.match(await mobileGateway.text(), /title="Gateway at phone width" src="\/gateways\/"/)
  const mobileCreate = await fetch(`${url}/_fixture/mobile/create`)
  assert.equal(mobileCreate.status, 200)
  assert.match(await mobileCreate.text(), /title="Create at phone width" src="\/create\/"/)
  assert.equal((await fetch(`${url}/_fixture/mobile/unknown`)).status, 404)
  const mobileContainers = await fetch(`${url}/_fixture/mobile/dev-containers`)
  assert.equal(mobileContainers.status, 200)
  assert.match(await mobileContainers.text(), /title="Dev Containers at phone width" src="\/dev-containers\/"/)
  const administration = await (await fetch(`${url}/v1/depot/operations`)).json()
  assert.equal(administration.operations.length, 6)
  assert.ok(administration.operations.every(operation => operation.name.startsWith('fixture.') && operation.annotations.readOnlyHint === true))
  const invocation = await fetch(`${url}/v1/depot/operations`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ operation: administration.operations[0].name, params: {} }) })
  assert.equal(invocation.status, 403)
  assert.match(html.headers.get('content-security-policy'), /frame-src 'none'/)
  assert.match(await (await fetch(`${url}/depot/`, { headers: { rsc: '1' } })).text(), /Actual export fixture/)
  assert.equal(await (await fetch(`${url}/depot/index.txt?_rsc=private-value`, { headers: { rsc: '1' } })).text(), 'RSC fixture')
  assert.equal(await (await fetch(`${url}/depot/__next._full.txt?artifact=private-value`)).text(), 'Segment fixture')
  assert.ok(requests.some((entry) => entry.path === '/depot/index.txt' && entry.rsc && entry.status === 200))
  assert.ok(!JSON.stringify(requests).includes('private-value'))
  assert.equal((await fetch(`${url}/auth/session`, { headers: { origin: 'https://example.invalid' } })).status, 403)
  const hostileHostStatus = await new Promise((done, reject) => get(`${url}/auth/session`, { headers: { host: 'example.invalid' } }, (response) => { response.resume(); done(response.statusCode) }).on('error', reject))
  assert.equal(hostileHostStatus, 403)
  assert.equal((await (await fetch(`${url}/auth/session`)).json()).user.email, 'fixture@example.invalid')
  assert.equal((await (await fetch(`${url}/v1/depot/providers`)).json()).length, 2)
  const post = (path, body) => fetch(`${url}${path}`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) })
  const setupState = await (await post('/v1/setup', { action: 'state', params: {} })).json()
  assert.equal(setupState.draft_stale, false)
  assert.equal(setupState.has_draft, false)
  const featureSettings = await (await post('/v1/setup', { action: 'settings.state', params: { section: 'features' } })).json()
  assert.equal(featureSettings.values['code_mode.enabled'], true)
  const surfaceSettings = await (await post('/v1/setup', { action: 'settings.state', params: { section: 'surfaces' } })).json()
  assert.equal(surfaceSettings.values.LABBY_MCP_GATEWAY_URL, 'https://labby.tootie.tv')
  assert.equal((await post('/v1/setup', { action: 'settings.config.update', params: {} })).status, 403)
  const compactTasks = await fetch(`${url}/_fixture/tasks-compact`)
  assert.equal(compactTasks.status, 200)
  assert.match(await compactTasks.text(), /width:1120px/)
  const loadouts = await (await post('/v1/gateway', { action: 'gateway.loadout.list_state', params: {} })).json()
  assert.equal(loadouts.length, 3)
  assert.ok(loadouts.every(loadout => loadout.name.startsWith('fixture-')))
  const mounts = await (await post('/v1/gateway', { action: 'gateway.protected_route.list_state', params: {} })).json()
  assert.equal(mounts[0].target.loadout, loadouts[0].name)
  assert.equal(mounts[0].public_host, 'fixture.example.invalid')
  assert.equal((await post('/v1/gateway', { action: 'gateway.loadout.list_state', params: { path: '/private' } })).status, 400)
  for (const action of ['gateway.loadout.add', 'gateway.loadout.patch', 'gateway.loadout.remove', 'gateway.loadout.stage_update', 'gateway.protected_route.add']) assert.equal((await post('/v1/gateway', { action, params: {} })).status, 403)
  const snippets = await (await post('/v1/snippets', { action: 'snippets.list', params: {} })).json()
  assert.equal(snippets.snippets.length, 8)
  assert.ok(snippets.snippets.every(snippet => snippet.name.startsWith('fixture-') && !Object.hasOwn(snippet, 'body')))
  const snippet = await (await post('/v1/snippets', { action: 'snippets.get', params: { name: snippets.snippets[0].name } })).json()
  assert.match(snippet.body, /synthetic visual QA/)
  assert.equal((await post('/v1/snippets', { action: 'snippets.get', params: { name: 'unknown' } })).status, 404)
  assert.equal((await post('/v1/snippets', { action: 'snippets.list', params: { path: '/private' } })).status, 400)
  for (const action of ['snippets.create', 'snippets.remove', 'snippets.exec', 'snippets.test', 'snippets.validate']) {
    assert.equal((await post('/v1/snippets', { action, params: { name: snippet.name } })).status, 403)
  }
  const metricsParams = { since_unix: 1788800000, until_unix: 1788886400, bucket_count: 24, timezone: 'America/Chicago', timezone_offset_minutes: -300, include_facets: false }
  const usageParams = { since_unix: metricsParams.since_unix, until_unix: metricsParams.until_unix }
  const usageRows = await (await post('/v1/gateway', { action: 'gateway.usage.calls', params: { ...usageParams, limit: 50, include_total: true } })).json()
  assert.equal(usageRows.calls.length, 50)
  assert.match(usageRows.next_cursor, /^fixture:/)
  const usageSummary = await (await post('/v1/gateway', { action: 'gateway.usage.metrics', params: { ...usageParams, bucket_count: 0, include_facets: true } })).json()
  assert.ok(usageSummary.total_calls > usageRows.calls.length)
  const failedRows = await (await post('/v1/gateway', { action: 'gateway.usage.calls', params: { ...usageParams, limit: 50, outcome: 'failed' } })).json()
  assert.ok(failedRows.calls.length > 0)
  assert.ok(failedRows.calls.every(call => call.outcome !== 'ok'))
  assert.equal((await post('/v1/gateway', { action: 'gateway.usage.calls', params: { ...usageParams, limit: 50, path: '/private' } })).status, 400)
  assert.equal((await post('/v1/gateway', { action: 'gateway.usage.clear', params: {} })).status, 403)
  const logRows = await (await post('/v1/server_logs', { action: 'server_logs.query', params: { limit: 250 } })).json()
  assert.equal(logRows.entries.length, 6)
  assert.equal(logRows.entries.filter(entry => entry.fields.upstream === 'Fixture Corpus').length, 3)
  const errorRows = await (await post('/v1/server_logs', { action: 'server_logs.query', params: { level: 'ERROR', query: 'timed out' } })).json()
  assert.equal(errorRows.entries.length, 1)
  assert.equal(errorRows.entries[0].kind, 'timeout')
  assert.equal((await post('/v1/server_logs', { action: 'server_logs.query', params: { path: '/private/log' } })).status, 400)
  assert.equal((await post('/v1/server_logs', { action: 'server_logs.clear', params: {} })).status, 403)
  const browserRows = await (await post('/v1/browser', { action: 'browser.list', params: {} })).json()
  assert.equal(browserRows.browsers.length, 2)
  assert.equal(browserRows.browsers.filter(browser => browser.connected).length, 1)
  const pairings = await (await post('/v1/browser', { action: 'browser.pairing.list', params: {} })).json()
  assert.equal(pairings.pairings[0].status, 'pending')
  assert.equal(pairings.pairings[0].browser_id, null)
  const documents = await (await post('/v1/browser', { action: 'browser.sessions', params: {} })).json()
  assert.equal(documents.sessions[0].enabled, false)
  assert.equal(documents.sessions[0].tools.length, 2)
  assert.ok(browserRows.browsers.some(browser => browser.id === documents.sessions[0].browser_id))
  assert.match(documents.sessions[0].origin, /\.invalid$/)
  assert.equal((await post('/v1/browser', { action: 'browser.list', params: { target: 'production' } })).status, 400)
  for (const action of ['browser.pairing.approve', 'browser.revoke', 'browser.session.enable', 'browser.execute']) assert.equal((await post('/v1/browser', { action, params: {} })).status, 403)
  const tools = await (await post('/v1/gateway/codemode/tools/search', { query: '', limit: 50 })).json()
  assert.equal(tools.total, 4)
  assert.equal(tools.results.filter(tool => tool.safety.read_only).length, 2)
  const toolDetail = await (await post('/v1/gateway/codemode/tools/describe', { target: tools.results[0].id })).json()
  assert.equal(toolDetail.id, tools.results[0].id)
  assert.match(toolDetail.typescript, /declare function search/)
  assert.equal((await post('/v1/gateway/codemode/tools/search', { query: '', limit: 51 })).status, 400)
  assert.equal((await post('/v1/gateway/codemode/tools/describe', { target: 'unknown' })).status, 404)
  assert.equal((await post('/v1/gateway/codemode/tools/execute', { target: tools.results[0].id })).status, 403)
  assert.equal((await post('/v1/gateway', { action: 'gateway.code_mode.set', params: { enabled: true } })).status, 403)
  const gatewayRows = await (await post('/v1/gateway', { action: 'gateway.list', params: {} })).json()
  const gatewayRuntime = await (await post('/v1/gateway', { action: 'gateway.mcp.list', params: {} })).json()
  assert.equal(gatewayRows.length, 3)
  assert.equal(gatewayRows.filter(row => row.connected).length, 2)
  assert.deepEqual(gatewayRuntime.map(row => row.name), gatewayRows.map(row => row.name))
  assert.ok(gatewayRows.every(row => new URL(row.config_summary.target).hostname.endsWith('.invalid')))
  for (const action of ['gateway.list', 'gateway.mcp.list']) {
    for (const params of [null, [], { target: 'production' }]) {
      assert.equal((await post('/v1/gateway', { action, params })).status, 400)
    }
  }
  for (const action of ['gateway.test', 'gateway.status', 'gateway.server.get', 'gateway.remove']) {
    assert.equal((await post('/v1/gateway', { action, params: {} })).status, 403)
  }
  const metricsResponse = await post('/v1/gateway', { action: 'gateway.usage.metrics', params: metricsParams })
  assert.equal(metricsResponse.status, 200)
  const metrics = await metricsResponse.json()
  assert.equal(metrics.timeseries.length, 24)
  assert.ok(metrics.total_calls > 0)
  assert.equal(metrics.timeseries.reduce((sum, bucket) => sum + bucket.calls, 0), metrics.total_calls)
  assert.equal((await post('/v1/gateway', { action: 'gateway.remove', params: { confirm: true } })).status, 403)
  for (const invalid of [{ bucket_count: 100000 }, { since_unix: -1 }, { until_unix: 1788800000 }, { until_unix: 4102444801 }, { upstream: 'production' }, { timezone: [] }]) {
    assert.equal((await post('/v1/gateway', { action: 'gateway.usage.metrics', params: { ...metricsParams, ...invalid } })).status, 400)
  }
  const discover = async (extra = {}) => (await post('/v1/depot/discover', { provider: null, query: '', limit: 50, ...extra })).json()
  const all = await discover()
  assert.equal(all.items.length, 6)
  assert.equal(all.highlights.popular.items.length, 6)
  assert.equal(all.highlights.team.items.length, 3)
  assert.equal(all.highlights.loadouts.items.length, 4)
  assert.ok(all.highlights.popular.items.every(item => all.items.some(row => row.artifactId === item.artifact.artifactId)))
  assert.equal(all.sourceOrigin, undefined)
  for (const feed of [undefined, 'new']) {
    const filtered = await discover({ sourceOrigin: 'mcp-registry', feed })
    assert.equal(filtered.sourceOrigin, 'mcp-registry')
    assert.equal(filtered.highlights, undefined)
    assert.equal(filtered.knownTotal, 1)
    assert.ok(filtered.items.every(row => row.sourceOrigin === 'mcp-registry'))
  }
  const emptyOrigin = await discover({ sourceOrigin: 'acp-registry' })
  assert.equal(emptyOrigin.sourceOrigin, 'acp-registry')
  assert.deepEqual(emptyOrigin.items, [])
  const newest = await discover({ feed: 'new' })
  assert.equal(newest.items.length, 5)
  assert.equal(newest.highlights, undefined)
  assert.equal(newest.rankingVersion, 'new/v1')
  assert.deepEqual(await discover({ feed: 'new' }), newest)
  assert.ok((await discover({ provider: 'team' })).items.every((row) => row.providerId === 'team'))
  assert.equal((await discover({ query: 'accessibility' })).items.length, 1)
  const first = all.items[0]
  const status = await (await fetch(`${url}/v1/depot/status`)).json()
  assert.equal(status.depot.enabled, true)
  assert.equal(status.depot.mutationAuthority, false)
  assert.equal((await (await fetch(`${url}/v1/depot/publish`)).json()).available, false)
  const library = async (params) => (await post('/v1/depot/operations', { operation: 'depot.artifacts.list', params })).json()
  const pageOne = await library({ limit: 2 })
  assert.equal(pageOne.schemaVersion, 'labby.depot-compatibility/v1')
  assert.equal(pageOne.result.total, 6)
  assert.deepEqual(pageOne.result.artifacts.map(row => row.id), all.items.slice(0, 2).map(row => row.id))
  const pageTwo = await library({ limit: 2, cursor: pageOne.result.nextCursor })
  assert.deepEqual(pageTwo.result.artifacts.map(row => row.id), all.items.slice(2, 4).map(row => row.id))
  const librarySearch = await library({ limit: 50, query: 'accessibility' })
  assert.equal(librarySearch.result.total, 1)
  assert.equal(librarySearch.result.nextCursor, undefined)
  assert.equal((await library({ limit: 50, query: 'no-such-artifact' })).result.total, 0)
  const libraryDetail = await (await post('/v1/depot/operations', { operation: 'depot.artifacts.get', params: { artifactId: first.id } })).json()
  assert.equal(libraryDetail.result.artifact.id, first.id)
  assert.equal(libraryDetail.result.artifact.readme.revisionId, first.currentRevisionId)
  for (const params of [{ limit: 0 }, { limit: 201 }, { limit: 2, cursor: 'arbitrary' }, { limit: 2, query: {} }]) assert.equal((await post('/v1/depot/operations', { operation: 'depot.artifacts.list', params })).status, 400)
  for (const operation of ['depot.artifacts.delete', 'depot.artifacts.publish', 'depot.unknown']) assert.equal((await post('/v1/depot/operations', { operation, params: {} })).status, 403)
  assert.equal((await post('/v1/depot/publish', { name: 'fixture', source: 'test' })).status, 403)
  const detail = await (await post('/v1/depot/artifacts/detail', { providerId: first.providerId, artifactId: first.artifactId })).json()
  assert.equal(detail.artifact.readme.revisionId, first.currentRevisionId)
  assert.deepEqual(detail.artifact.descriptor.tags, ['documentation', 'review'])
  assert.equal(detail.artifact.provenance.originalFormat, 'claude-skill')
  const membership = await (await post('/v1/artifacts', { action: 'artifacts.depot_membership', params: { items: [{ connection_id: first.providerId, artifact_id: first.artifactId, revision_id: first.currentRevisionId }] } })).json()
  assert.equal(membership.items[0].status, 'exact_revision_present')
  assert.equal((await (await post('/v1/artifacts', { action: 'artifacts.list', params: { limit: 1 } })).json()).library_version, 3)
  assert.deepEqual((await (await post('/v1/artifacts', { action: 'artifacts.list_connections' })).json()).connections.map(row => row.id), ['catalog', 'team'])
  for (const action of ['artifacts.activate', 'artifacts.import', 'artifacts.fork', 'artifacts.delete']) assert.equal((await post('/v1/artifacts', { action, params: {} })).status, 403)
  assert.equal((await post('/v1/depot/providers', {})).status, 403)
  assert.equal((await fetch(`${url}/auth/logout`, { method: 'DELETE' })).status, 403)
  assert.equal((await fetch(`${url}/v1/unknown`)).status, 404)
})
