import { Box, Clipboard, Cloud, Copy, FileUp, Play, RefreshCw, Search, Share2, Trash2 } from 'lucide-react'

import { AppHeader } from '@/components/app-header'
import { MockSurfaceBadge } from '@/components/console/mock-surface-badge'

const card = 'overflow-hidden rounded-aurora-2 border border-aurora-border-default/55 bg-[linear-gradient(180deg,var(--aurora-panel-strong-top),var(--aurora-panel-strong))] shadow-[var(--aurora-shadow-medium),inset_0_1px_0_rgba(255,255,255,0.04)]'
const control = 'inline-flex h-8 items-center gap-1.5 rounded-[9px] border border-aurora-border-default bg-aurora-control-surface px-3 text-[11px] font-semibold text-aurora-text-muted disabled:cursor-not-allowed disabled:opacity-60'

function Notice({ screen }: { screen: string }) {
  return <div className="flex items-start gap-3 rounded-aurora-1 border border-aurora-warn/30 bg-[color-mix(in_srgb,var(--aurora-warn)_8%,var(--aurora-panel-strong))] px-4 py-3 text-[12px] text-aurora-text-muted"><MockSurfaceBadge className="shrink-0" /><p>This {screen} page reproduces the approved mock. Every file, image, metric, identity, credential, and action is illustrative; no controls call a Labby service.</p></div>
}

const stashFiles = [
  ['fleet-snapshot.json', 'stash://me/fleet-snapshot.json', 'agents', '412 KB'],
  ['reconcile-notes.md', 'stash://me/reconcile-notes.md', 'private', '18 KB'],
  ['gateway-trace.log', 'stash://me/gateway-trace.log', 'agents', '96 MB'],
  ['schema.prisma', 'stash://me/schema.prisma', 'agents', '11 KB'],
  ['topology.png', 'stash://me/topology.png', 'private', '1.2 MB'],
  ['usage-2026-08.csv', 'stash://me/usage-2026-08.csv', 'agents', '2.1 MB'],
] as const

export function MockStashPage() {
  return <><AppHeader breadcrumbs={[{ label: 'Stash' }]} /><section data-screen-label="Stash" data-mock-region="stash" aria-label="Stash mock data" className="flex flex-col gap-[14px]">
    <section data-hero="1" className={card}><div className="flex flex-wrap items-end justify-between gap-4 px-6 pt-[22px] pb-4"><div><div className="flex items-center gap-2.5"><span className="text-[10.5px] font-bold uppercase tracking-[.16em] text-aurora-text-muted">Control Plane · Stash</span><MockSurfaceBadge /></div><h1 className="mt-2 font-display text-[30px] font-extrabold text-aurora-text-primary">Stash</h1><p className="mt-[7px] max-w-[650px] text-[12.5px] leading-[1.55] text-aurora-text-muted">A scratch drive for you and your agents. Drop a file here and it is addressable at stash:// from any session without leaving the console.</p></div><button disabled className={`${control} h-9 border-aurora-accent-primary/40 text-aurora-accent-strong`}><FileUp className="size-3.5" />Upload</button></div><div className="grid grid-cols-2 border-t border-aurora-border-default/50 bg-[var(--gw0-0_30)] lg:grid-cols-4">{[['Files','6','stashed'],['Size','2.4 GB','of 10 GB'],['Agent Reads','96','last 7 days'],['Shared','4','reachable']].map(([k,v,s])=><div key={k} className="border-l border-aurora-border-default/40 px-5 py-3 first:border-l-0"><span className="text-[9.5px] font-bold uppercase tracking-[.12em] text-aurora-text-muted">{k}</span><div className="mt-1"><b className="font-display text-[21px] text-aurora-text-primary">{v}</b><span className="ml-2 text-[10.5px] text-aurora-text-muted">{s}</span></div></div>)}</div></section>
    <div className="grid place-items-center rounded-aurora-2 border border-dashed border-aurora-accent-primary/35 bg-[color-mix(in_srgb,var(--aurora-accent-primary)_5%,transparent)] px-4 py-6 text-center"><FileUp className="size-5 text-aurora-accent-strong" /><b className="mt-2 text-[12px] text-aurora-text-primary">Drop files to stash them</b><span className="mt-1 text-[10.5px] text-aurora-text-muted">agents read this over MCP as stash:// · Mock</span></div>
    <div className="flex flex-wrap items-center gap-2"><span className="text-[10px] font-bold uppercase tracking-[.14em] text-aurora-text-muted">Files</span><label className="ml-auto flex h-8 min-w-[240px] items-center gap-2 rounded-[9px] border border-aurora-border-default bg-aurora-control-surface px-3"><Search className="size-3.5 text-aurora-text-muted" /><input disabled aria-label="Filter stash" placeholder="Filter 6 files…" className="w-full bg-transparent text-[11px] outline-none placeholder:text-aurora-text-muted" /></label>{['All','Doc','Data','Code','Image','Archive'].map((x,i)=><button key={x} disabled aria-pressed={i===0} className={`${control} ${i===0?'border-aurora-accent-primary/40 text-aurora-accent-strong':''}`}>{x}</button>)}</div>
    <section className={card}><div className="grid grid-cols-[minmax(260px,1fr)_90px_80px_138px] gap-3 border-b border-aurora-border-strong bg-[var(--gw0-0_48)] px-4 py-2.5 text-[10px] font-bold uppercase tracking-[.13em] text-aurora-text-muted"><span>Name</span><span>Access</span><span>Size</span><span /></div>{stashFiles.map(([name,path,access,size])=><article key={name} data-mock-region="stash-file" className="grid grid-cols-[minmax(260px,1fr)_90px_80px_138px] items-center gap-3 border-t border-aurora-border-default/45 px-4 py-3 first:border-t-0"><div><h3 className="font-display text-[12.5px] font-bold text-aurora-text-primary">{name}</h3><p className="font-mono text-[10.5px] text-aurora-text-muted">{path}</p></div><span className="w-fit rounded-full border border-aurora-accent-primary/25 px-2 py-1 text-[10px] text-aurora-accent-strong">{access}</span><span className="text-[10.5px] text-aurora-text-muted">{size}</span><div className="flex justify-end gap-1"><button disabled aria-label="Copy stash path" className={control}><Copy className="size-3" /></button><button disabled aria-label="Share file" className={control}><Share2 className="size-3" /></button><button disabled aria-label="Remove from stash" className={control}><Trash2 className="size-3" /></button></div></article>)}</section><Notice screen="Stash" />
  </section></>
}

const containers = [
  ['platform-base','Ready','Ubuntu 24.04 · 1.9 GB · built 2d ago',['node.js','python','rust','docker','anthropic'],'38 pulls · 9 members'],
  ['rust-heavy','Ready','Debian 12 · 2.4 GB · built 1d ago',['rust','postgresql','docker','openai'],'12 pulls · 4 members'],
  ['edge-minimal','Building','Alpine 3.21 · 412 MB · build started 4m ago',['go','bun','github copilot'],'Layer 4/7 · installing toolchains'],
] as const

export function MockContainersPage() {
  return <><AppHeader breadcrumbs={[{ label: 'Dev Containers' }]} /><section data-screen-label="Dev Containers" data-mock-region="containers" aria-label="Dev Containers mock data" className="flex flex-col gap-[14px]">
    <section data-hero="1" className={card}><div className="flex flex-wrap items-end justify-between gap-4 px-6 py-[22px]"><div><div className="flex items-center gap-2.5"><span className="text-[10.5px] font-bold uppercase tracking-[.16em] text-aurora-text-muted">Team · Incus</span><MockSurfaceBadge /></div><h1 className="mt-2 font-display text-[30px] font-extrabold text-aurora-text-primary">Dev Containers</h1><p className="mt-[7px] max-w-[680px] text-[12.5px] leading-[1.55] text-aurora-text-muted">System containers your team pulls onto their own machine. You define distro, toolchains, agents and loadouts — resource limits and mounts stay with whoever runs it.</p></div><button disabled className={`${control} h-9 border-aurora-accent-primary/40 text-aurora-accent-strong`}><Box className="size-3.5" />New Container</button></div></section>
    <div className="grid gap-3 lg:grid-cols-3">{containers.map(([name,status,meta,tools,usage])=><article key={name} data-mock-region="container-card" className={`${card} flex min-h-[245px] flex-col p-4`}><div className="flex items-start justify-between gap-3"><div className="grid size-10 place-items-center rounded-[12px] border border-aurora-accent-primary/25 bg-[color-mix(in_srgb,var(--aurora-accent-primary)_9%,transparent)]"><Box className="size-5 text-aurora-accent-strong" /></div><span className={`rounded-md border px-2 py-1 text-[9.5px] font-bold ${status==='Ready'?'border-aurora-success/30 text-aurora-success':'border-aurora-warn/30 text-aurora-warn'}`}>{status}</span></div><h2 className="mt-3 font-display text-[16px] font-extrabold text-aurora-text-primary">{name}</h2><p className="mt-1 text-[10.5px] text-aurora-text-muted">{meta}</p><div className="mt-4 flex flex-wrap gap-1.5">{tools.map(t=><span key={t} className="rounded-full border border-aurora-border-default px-2 py-1 text-[9.5px] text-aurora-text-muted">{t}</span>)}</div><p className="mt-auto pt-4 text-[10.5px] text-aurora-text-muted">{usage}</p><div className="mt-3 flex gap-2"><button disabled className={control}><Clipboard className="size-3" />Copy pull command</button><button disabled className={`${control} ml-auto`}><RefreshCw className="size-3" />Rebuild</button></div></article>)}</div><Notice screen="Dev Containers" />
  </section></>
}

const traffic = [42,38,30,26,22,25,34,55,72,84,91,88,79,83,95,99,92,80,68,57,50,46,44,40]
const loadouts = [['project-a-loadout','10 artifacts · 4 MCP servers · 12 tools exposed','#project-a','4h ago'],['platform-core','6 artifacts · 2 MCP servers · 8 tools exposed','#platform','2d ago'],['oncall-loadout','5 artifacts · 3 MCP servers · 9 tools exposed','#support','5d ago']] as const

export function MockInstancePage() {
  return <><AppHeader breadcrumbs={[{ label: 'Labby' }]} /><section data-screen-label="Labby Instance" data-mock-region="instance" aria-label="Labby Instance mock data" className="flex flex-col gap-[14px]">
    <section data-hero="1" className={card}><div className="flex flex-wrap items-end justify-between gap-4 px-6 pt-[22px] pb-4"><div><div className="flex items-center gap-2.5"><span className="text-[10.5px] font-bold uppercase tracking-[.16em] text-aurora-text-muted">Team · Hosted</span><span className="inline-flex items-center gap-1.5 text-[10.5px] font-semibold text-aurora-success"><span className="size-1.5 rounded-full bg-aurora-success" />Running</span><MockSurfaceBadge /></div><h1 className="mt-2 font-display text-[30px] font-extrabold text-aurora-text-primary">Labby Instance</h1><p className="mt-[7px] max-w-[620px] text-[12.5px] leading-[1.55] text-aurora-text-muted">Your team’s hosted gateway. Members connect with their own token — nobody deploys, ingests or babysits a server.</p></div><div className="flex gap-2"><button disabled className={control}><RefreshCw className="size-3" />Restart</button><button disabled className={`${control} border-aurora-accent-primary/40 text-aurora-accent-strong`}><Cloud className="size-3" />Deploy Loadout</button></div></div><div className="grid grid-cols-2 border-t border-aurora-border-default/50 bg-[var(--gw0-0_30)] lg:grid-cols-5">{[['Seats','9','of 25'],['Connected','6','right now'],['Artifacts','284','ingested'],['Calls','1.2k','per hour'],['P99','48 ms','gateway']].map(([k,v,s])=><div key={k} className="border-l border-aurora-border-default/40 px-5 py-3 first:border-l-0"><span className="text-[9.5px] font-bold uppercase tracking-[.12em] text-aurora-text-muted">{k}</span><div className="mt-1"><b className="font-display text-[21px] text-aurora-text-primary">{v}</b><span className="ml-2 text-[10.5px] text-aurora-text-muted">{s}</span></div></div>)}</div></section>
    <div className="grid gap-3 lg:grid-cols-2"><section className={`${card} p-4`}><div className="flex items-center justify-between"><h2 className="text-[10px] font-bold uppercase tracking-[.14em] text-aurora-text-muted">Connection</h2><button disabled className={control}>Rotate Token</button></div>{[['MCP Endpoint','https://labby-tootie-tv.depot.sh/mcp'],['CLI','labby connect --team tootie-tv --token dpt_live_9f2c…']].map(([k,v])=><div key={k} className="mt-3 rounded-[9px] border border-aurora-border-default bg-[var(--gw4-0_62)] p-3"><span className="text-[9.5px] font-bold uppercase text-aurora-text-muted">{k}</span><div className="mt-1 flex gap-2"><code className="min-w-0 flex-1 truncate text-[10.5px] text-aurora-accent-strong">{v}</code><button disabled className={control}><Copy className="size-3" />Copy</button></div></div>)}</section><section className={`${card} p-4`}><div className="flex justify-between"><h2 className="text-[10px] font-bold uppercase tracking-[.14em] text-aurora-text-muted">Traffic · 24h</h2><span className="text-[10.5px] text-aurora-text-muted">28.4k calls · 0.4% errors</span></div><div className="mt-5 flex h-24 items-end gap-1">{traffic.map((h,i)=><span key={i} title={`${String(i).padStart(2,'0')}:00 · mock calls`} className="flex-1 rounded-t-sm bg-aurora-accent-primary/65" style={{height:`${h}%`}} />)}</div></section></div>
    <div className="grid gap-3 lg:grid-cols-[1.4fr_1fr]"><section className={card}><div className="flex items-center justify-between border-b border-aurora-border-default/50 bg-[var(--gw0-0_38)] px-4 py-2.5"><h2 className="text-[10px] font-bold uppercase tracking-[.14em] text-aurora-text-muted">Loadouts Deployed</h2><span className="text-[10.5px] text-aurora-success">3 live</span></div>{loadouts.map(([name,detail,scope,when])=><div key={name} data-mock-region="instance-loadout" className="grid grid-cols-[minmax(180px,1fr)_100px_70px_90px] items-center gap-3 border-t border-aurora-border-default/45 px-4 py-3 first:border-t-0"><div><b className="font-display text-[12.5px] text-aurora-text-primary">{name}</b><p className="text-[10.5px] text-aurora-text-muted">{detail}</p></div><span className="rounded-full border border-aurora-accent-primary/25 px-2 py-1 text-[10px] text-aurora-accent-strong">{scope}</span><span className="text-[10.5px] text-aurora-text-muted">{when}</span><button disabled className={control}><Play className="size-3" />Redeploy</button></div>)}</section><section className={`${card} p-4`}><h2 className="text-[10px] font-bold uppercase tracking-[.14em] text-aurora-text-muted">Instance</h2>{[['Region','eu-west · Amsterdam'],['Version','labby 0.24.0'],['Uptime','18d 4h'],['Plan','Team · 25 seats'],['Backups','nightly · 02:00 UTC'],['Last ingest','11m ago']].map(([k,v])=><div key={k} className="flex justify-between border-t border-aurora-border-default/40 py-2.5 first:mt-2"><span className="text-[10.5px] text-aurora-text-muted">{k}</span><b className="text-[10.5px] text-aurora-text-primary">{v}</b></div>)}</section></div><Notice screen="Labby Instance" />
  </section></>
}
