import type { ComponentType } from 'react'
import type { LucideIcon } from 'lucide-react'
import {
  Activity, Archive, Bot, Box, ChevronRight, Container, Copy, FileCode2,
  FolderGit2, FolderKanban, GitFork, Globe2, Heart, Library, MessageSquare,
  MoreHorizontal, Plus, Radio, Server, Share2, Shield, Sparkles, Star, Users,
} from 'lucide-react'

import { AppHeader } from '@/components/app-header'
import { MockSurfaceBadge } from '@/components/console/mock-surface-badge'

export type MockTeamPageKind = 'overview' | 'library' | 'projects' | 'activity' | 'stash'

const CARD = 'overflow-hidden rounded-aurora-2 border border-[color-mix(in_srgb,var(--aurora-border-default)_45%,var(--aurora-page-bg))] bg-[linear-gradient(180deg,var(--aurora-panel-strong-top),var(--aurora-panel-strong))] shadow-[var(--aurora-shadow-medium),inset_0_1px_0_rgba(255,255,255,0.04)]'
const MOCK_BUTTON = 'inline-flex h-8 cursor-not-allowed items-center justify-center gap-1.5 rounded-[9px] border border-aurora-border-default/70 bg-aurora-control-surface px-3 text-[11px] font-semibold text-aurora-text-secondary opacity-65'

function MockButton({ children, accent = false }: { children: React.ReactNode; accent?: boolean }) {
  return <button type="button" disabled title="Unavailable — mock surface" className={`${MOCK_BUTTON} ${accent ? 'border-aurora-accent-pink-deep/40 text-aurora-accent-pink' : ''}`}>{children}</button>
}

function Avatars({ people = ['J', 'AC', 'BO', 'CR', 'DP'] }: { people?: string[] }) {
  return <div className="hidden -space-x-2 sm:flex" aria-label="Illustrative team members">{people.map((initials, index) => <span key={initials} className="grid size-7 place-items-center rounded-full border-2 border-aurora-panel-strong bg-aurora-control-surface text-[8.5px] font-bold text-aurora-accent-strong" style={{ zIndex: people.length - index }}>{initials}</span>)}</div>
}

function TeamHero({ title, description, action, icon: Icon, stats }: { title: string; description: string; action: string; icon: LucideIcon; stats?: Array<[string, string, string]> }) {
  return <section data-hero="1" className="overflow-hidden rounded-aurora-3 border border-[color-mix(in_srgb,var(--aurora-border-default)_45%,var(--aurora-page-bg))] bg-[linear-gradient(180deg,var(--aurora-panel-strong-top),var(--aurora-panel-strong))] shadow-[var(--aurora-shadow-strong),inset_0_1px_0_rgba(255,255,255,0.05)]">
    <div className="flex flex-wrap items-start justify-between gap-4 px-6 pt-6 pb-[18px]">
      <div className="flex min-w-0 flex-col items-start gap-3.5 sm:flex-row"><span className="grid size-[52px] shrink-0 place-items-center rounded-[16px] border border-aurora-success/30 bg-[color-mix(in_srgb,var(--aurora-success)_14%,transparent)] font-display text-[19px] font-extrabold text-aurora-success">TO</span><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="text-[10.5px] font-bold uppercase tracking-[0.16em] text-aurora-text-muted">Team · tootie.tv</span><span className="rounded-[4px] border border-aurora-accent-pink-deep/40 bg-[color-mix(in_srgb,var(--aurora-accent-pink)_9%,transparent)] px-2 py-0.5 text-[9px] font-bold tracking-[0.1em] text-aurora-accent-pink">PAID</span><MockSurfaceBadge /></div><div className="mt-[7px] flex items-center gap-2.5"><Icon className="size-6 shrink-0 text-aurora-accent-pink" /><h1 className="font-display text-[30px] leading-[1.04] font-extrabold text-aurora-text-primary">{title}</h1></div><p className="mt-[7px] max-w-[620px] text-[12.5px] leading-[1.55] text-aurora-text-muted">{description}</p></div></div>
      <div className="flex items-center gap-3"><Avatars /><MockButton accent><Plus className="size-3.5" />{action}</MockButton></div>
    </div>
    {stats ? <div className="grid grid-cols-2 border-t border-aurora-border-default/55 bg-[var(--gw0-0_30)] lg:grid-cols-5">{stats.map(([name, value, detail]) => <div key={name} className="border-l border-aurora-border-default/40 px-5 py-3 first:border-l-0"><div className="text-[9.5px] font-bold uppercase tracking-[0.12em] text-aurora-text-muted">{name}</div><div className="mt-1 flex items-baseline gap-2"><span className="font-display text-[21px] font-extrabold text-aurora-text-primary">{value}</span><span className="text-[10.5px] text-aurora-text-muted">{detail}</span></div></div>)}</div> : null}
  </section>
}

function MockNotice() {
  return <div className="flex flex-col items-start gap-2.5 rounded-aurora-1 border border-aurora-warn/30 bg-[color-mix(in_srgb,var(--aurora-warn)_8%,var(--aurora-panel-strong))] px-4 py-3 text-[12px] leading-[1.55] text-aurora-text-muted sm:flex-row sm:gap-3"><MockSurfaceBadge className="mt-0.5" /><p>This team workspace is a visual mock. Names, membership, projects, files, and activity are illustrative; no controls call a Labby service.</p></div>
}

function SectionHeader({ icon: Icon, title, meta }: { icon: LucideIcon; title: string; meta?: string }) {
  return <div className="flex items-center gap-2 border-b border-aurora-border-default/70 bg-[var(--gw0-0_38)] px-4 py-2.5"><Icon className="size-3.5 text-aurora-accent-pink" /><h2 className="text-[10px] font-bold uppercase tracking-[0.14em] text-aurora-text-muted">{title}</h2>{meta ? <span className="ml-auto text-[10.5px] text-aurora-text-muted">{meta}</span> : null}</div>
}

function TeamOverview() {
  const launchers: Array<[string, string, LucideIcon]> = [['Library', '40 shared artifacts', Library], ['Projects', '3 with bound repos', FolderKanban], ['Dev Containers', '3 images · 1 building', Container], ['Labby', 'hosted · eu-west · 9 seats', Server], ['Stash', '46 files · shared', Archive], ['Activity', '12 new since yesterday', Activity]]
  const projects = [['Project A', '#project-a · 2 repos · 2 loadouts', '9h'], ['Project B', '#project-b · 1 repo · 1 loadout', '5h'], ['Platform', '#platform · 2 repos · 1 loadout', '1d']]
  return <><TeamHero title="tootie.tv" description="Homelab and agent infrastructure. One artifact repository, one hosted Labby, and a container per project." action="Invite" icon={Shield} stats={[["Members", "9", "of 25"], ["Projects", "3", "active"], ["Artifacts", "40", "shared"], ["Sessions", "2", "running now"], ["Pending", "3", "submissions"]]} /><MockNotice />
    <section data-mock-region="team-overview-launchers" className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{launchers.map(([title, detail, Icon]) => <article key={title} className={`${CARD} flex min-h-[104px] items-center gap-4 px-4 py-4`}><span className="grid size-10 shrink-0 place-items-center rounded-[12px] border border-aurora-accent-primary/20 bg-[color-mix(in_srgb,var(--aurora-accent-primary)_9%,transparent)]"><Icon className="size-[18px] text-aurora-accent-strong" /></span><div><h2 className="font-display text-[14px] font-bold text-aurora-text-primary">{title}</h2><p className="mt-1 text-[11px] text-aurora-text-muted">{detail}</p></div><ChevronRight className="ml-auto size-4 text-aurora-text-muted/60" /></article>)}</section>
    <div className="grid gap-3 xl:grid-cols-[1.35fr_0.85fr]"><section className={CARD} data-mock-region="team-overview-projects"><SectionHeader icon={FolderKanban} title="Projects" meta="3 active" />{projects.map(([name, detail, time]) => <div key={name} className="flex items-center gap-3 border-t border-aurora-border-default/45 px-4 py-3 first:border-t-0"><span className="grid size-8 place-items-center rounded-[9px] bg-aurora-control-surface"><FolderGit2 className="size-4 text-aurora-accent-strong" /></span><div><div className="text-[12px] font-semibold text-aurora-text-primary">{name}</div><div className="mt-0.5 text-[10.5px] text-aurora-text-muted">{detail}</div></div><span className="ml-auto text-[10.5px] text-aurora-text-muted">{time}</span></div>)}</section><section className={CARD} data-mock-region="team-overview-needs-you"><SectionHeader icon={Radio} title="Needs You" meta="3 open" />{[['Artifact submissions', '3 waiting for review'], ['edge-minimal', 'Building · 4m'], ['Dependency Bump', 'Paused · needs approval']].map(([name, detail]) => <div key={name} className="flex items-center gap-3 border-t border-aurora-border-default/45 px-4 py-3 first:border-t-0"><span className="size-1.5 rounded-full bg-aurora-warn" /><div><div className="text-[11.5px] font-semibold text-aurora-text-primary">{name}</div><div className="mt-0.5 text-[10.5px] text-aurora-text-muted">{detail}</div></div></div>)}</section></div>
    <section className={CARD} data-mock-region="team-overview-members"><SectionHeader icon={Users} title="Members" meta="9 of 25 seats" /><div className="grid gap-px bg-aurora-border-default/35 sm:grid-cols-2 xl:grid-cols-3">{[['jmagar', 'Owner'], ['alice chen', 'Admin'], ['ben okafor', 'Member'], ['carla ruiz', 'Member'], ['dev patel', 'Member'], ['erin walsh', 'Member']].map(([name, role]) => <div key={name} className="flex items-center gap-3 bg-aurora-panel-strong px-4 py-3"><span className="grid size-8 place-items-center rounded-full bg-aurora-control-surface text-[9px] font-bold text-aurora-accent-strong">{name.split(' ').map(part => part[0]).join('').toUpperCase()}</span><span className="text-[11.5px] font-semibold text-aurora-text-primary">{name}</span><span className="ml-auto text-[10px] text-aurora-text-muted">{role}</span></div>)}</div></section>
  </>
}

const artifactRows = [['Agent', 'rust-reviewer', 'carla ruiz', '#project-b', '5h'], ['Skill', 'repo-triage', 'alice chen', '#project-a', '7h'], ['Command', '/ship', 'jmagar', '#project-a', '9h'], ['Loadout', 'project-a-loadout', 'jmagar', '#project-a', '11h'], ['Hook', 'cost-ceiling', 'felix nagy', '#platform', '1d'], ['Server', 'labby', 'jmagar', '#shared', '1d'], ['Template', 'incident-postmortem', 'erin walsh', '#support', '2d'], ['Loadout', 'oncall-loadout', 'dev patel', '#support', '2d'], ['Command', '/scope-audit', 'ben okafor', '#project-b', '3d'], ['Agent', 'deploy-warden', 'gia moreno', '#platform', '4d']]

function TeamLibrary() {
  const submissions = [['AC', 'rust-reviewer', '+48 −12'], ['BO', '/scope-audit', '+31 −4'], ['GM', 'project-a-loadout', '+9 −17']]
  return <><TeamHero title="Team Library" description="The tootie.tv artifact repository. Share agents, skills, commands, hooks, and loadouts with the people and projects that need them." action="Invite Members" icon={Library} /><MockNotice />
    <div className="flex gap-1 border-b border-aurora-border-default/60" data-mock-region="team-library-tabs">{['Artifacts', 'Members & Groups', 'Public Page'].map((tab, index) => <button key={tab} type="button" disabled className={`cursor-not-allowed border-b-2 px-4 py-2.5 text-[11.5px] font-semibold ${index === 0 ? 'border-aurora-accent-pink text-aurora-text-primary' : 'border-transparent text-aurora-text-muted'}`}>{tab}</button>)}</div>
    <section className={CARD} data-mock-region="team-library-submissions"><SectionHeader icon={GitFork} title="Pending Submissions" meta="3 awaiting review" />{submissions.map(([initials, name, diff]) => <div key={name} className="flex flex-wrap items-center gap-3 border-t border-aurora-border-default/45 px-4 py-3 first:border-t-0"><span className="grid size-8 place-items-center rounded-full bg-aurora-control-surface text-[9px] font-bold text-aurora-accent-strong">{initials}</span><div className="min-w-[150px] flex-1"><div className="font-mono text-[11.5px] font-semibold text-aurora-text-primary">{name}</div><div className="mt-0.5 text-[10px] text-aurora-text-muted">Submission ready for team review</div></div><span className="font-mono text-[10.5px] text-aurora-success">{diff}</span><MockButton>Review Diff</MockButton><MockButton accent>Merge</MockButton></div>)}</section>
    <section className={CARD} data-mock-region="team-library-artifacts"><SectionHeader icon={Library} title="Shared Artifacts" meta="40 shared" /><div className="flex flex-wrap gap-1.5 border-b border-aurora-border-default/50 px-4 py-3">{['All', '#project-a', '#project-b', '#platform', '#support', '#shared'].map((filter, index) => <button key={filter} type="button" disabled className={`cursor-not-allowed rounded-full border px-2.5 py-1 text-[10px] font-semibold ${index === 0 ? 'border-aurora-accent-primary/40 bg-aurora-accent-primary/10 text-aurora-accent-strong' : 'border-aurora-border-default/60 text-aurora-text-muted'}`}>{filter}</button>)}</div><div className="hidden grid-cols-[90px_minmax(180px,1.3fr)_minmax(110px,1fr)_120px_65px] gap-3 border-b border-aurora-border-default/45 px-4 py-2 text-[9px] font-bold uppercase tracking-[0.12em] text-aurora-text-muted sm:grid"><span>Kind</span><span>Artifact</span><span>Owner</span><span>Access</span><span>Updated</span></div>{artifactRows.map(([kind, name, owner, access, updated]) => <div key={name} className="grid gap-2 border-t border-aurora-border-default/40 px-4 py-3 first:border-t-0 sm:grid-cols-[90px_minmax(180px,1.3fr)_minmax(110px,1fr)_120px_65px] sm:items-center"><span className="text-[10px] font-semibold text-aurora-accent-pink">{kind}</span><span className="font-mono text-[11px] font-semibold text-aurora-text-primary">{name}</span><span className="text-[10.5px] text-aurora-text-muted">{owner}</span><span className="w-fit rounded-full bg-aurora-control-surface px-2 py-1 text-[9.5px] text-aurora-accent-strong">{access}</span><span className="text-[10px] text-aurora-text-muted">{updated}</span></div>)}</section>
  </>
}

function TeamProjects() {
  return <><TeamHero title="Projects" description="Bind a tag to repositories, a loadout, a dev container, and the members working together." action="New Project" icon={FolderKanban} /><MockNotice />
    <div className="grid gap-3 xl:grid-cols-[250px_minmax(0,1fr)]"><aside className={CARD} data-mock-region="team-project-selector"><SectionHeader icon={FolderKanban} title="3 active" />{[['Project A', '#project-a', '4'], ['Project B', '#project-b', '3'], ['Platform', '#platform', '3']].map(([name, tag, count], index) => <button key={name} type="button" disabled className={`flex w-full cursor-not-allowed items-center gap-3 border-t border-aurora-border-default/45 px-4 py-3 text-left first:border-t-0 ${index === 0 ? 'bg-aurora-accent-primary/8' : ''}`}><span className={`size-2 rounded-full ${index === 0 ? 'bg-aurora-accent-pink' : 'bg-aurora-text-muted/35'}`} /><span><span className="block text-[11.5px] font-semibold text-aurora-text-primary">{name}</span><span className="mt-0.5 block text-[10px] text-aurora-text-muted">{tag}</span></span><span className="ml-auto text-[10px] text-aurora-text-muted">{count}</span></button>)}</aside>
      <div className="flex min-w-0 flex-col gap-3"><section className={CARD} data-mock-region="team-project-detail"><div className="flex flex-wrap items-start justify-between gap-3 px-5 py-4"><div><div className="text-[10px] font-semibold text-aurora-accent-pink">#project-a</div><h2 className="mt-1 font-display text-[20px] font-extrabold text-aurora-text-primary">Project A</h2><p className="mt-1 max-w-xl text-[11px] leading-5 text-aurora-text-muted">Gateway and artifact delivery work for the next Labby release.</p></div><Avatars people={['J', 'AC', 'BO', 'GM']} /></div><div className="grid grid-cols-2 border-t border-aurora-border-default/50 lg:grid-cols-4">{[['Artifacts', '14'], ['Members', '4'], ['Sessions', '2'], ['Tasks', '2']].map(([label, value]) => <div key={label} className="border-l border-aurora-border-default/40 px-4 py-3 first:border-l-0"><div className="text-[9px] uppercase tracking-wider text-aurora-text-muted">{label}</div><div className="mt-1 font-display text-lg font-bold text-aurora-text-primary">{value}</div></div>)}</div></section>
        <div className="grid gap-3 lg:grid-cols-2"><ProjectList icon={FolderGit2} title="Repositories (2)" rows={[['tootie-tv/labby', 'Rust · 4 PRs'], ['tootie-tv/depot', 'TypeScript · 2 PRs']]} region="repositories" /><ProjectList icon={Box} title="Loadouts (2)" rows={[['project-a-loadout', '10 artifacts'], ['platform-core', '6 artifacts']]} region="loadouts" /><ProjectList icon={Container} title="Dev Containers (1)" rows={[['platform-base', 'Ubuntu 24.04']]} region="containers" /><ProjectList icon={Sparkles} title="Key Artifacts (3)" rows={[['/ship', 'Command'], ['repo-triage', 'Skill'], ['rust-reviewer', 'Agent']]} region="artifacts" /></div>
        <section className={CARD} data-mock-region="team-project-updates"><SectionHeader icon={MessageSquare} title="Project Updates" />{[['jmagar', 'Cutover checklist is ready for review.', '9h'], ['alice chen', 'Gateway smoke test is green on platform-base.', '12h']].map(([name, update, time]) => <div key={update} className="flex gap-3 border-t border-aurora-border-default/45 px-4 py-3 first:border-t-0"><span className="grid size-7 shrink-0 place-items-center rounded-full bg-aurora-control-surface text-[8px] font-bold text-aurora-accent-strong">{name[0].toUpperCase()}</span><div><div className="text-[10px] font-semibold text-aurora-text-primary">{name} <span className="font-normal text-aurora-text-muted">· {time}</span></div><p className="mt-1 text-[11px] text-aurora-text-secondary">{update}</p></div></div>)}<div className="flex justify-end border-t border-aurora-border-default/45 px-4 py-3"><MockButton>Post</MockButton></div></section>
      </div></div>
  </>
}

function ProjectList({ icon, title, rows, region }: { icon: LucideIcon; title: string; rows: string[][]; region: string }) {
  return <section className={CARD} data-mock-region={`team-project-${region}`}><SectionHeader icon={icon} title={title} />{rows.map(([name, detail]) => <div key={name} className="border-t border-aurora-border-default/45 px-4 py-3 first:border-t-0"><div className="font-mono text-[11px] font-semibold text-aurora-text-primary">{name}</div><div className="mt-1 text-[10px] text-aurora-text-muted">{detail}</div></div>)}</section>
}

const activityRows: Array<[LucideIcon, string, string, string]> = [[Bot, 'carla ruiz updated rust-reviewer', 'Added unsafe-block rationale · #project-b', '5h'], [GitFork, 'ben okafor forked changelog-writer', 'Tracking upstream changes in the team library', '7h'], [MessageSquare, 'jmagar posted Project A cutover', 'Read before Monday · #project-a', '9h'], [Star, 'gia moreno starred secrets-sweeper', 'Now 1.7k stars', '11h'], [MessageSquare, 'alice chen commented on /ship', '“This should become the default release path.”', '13h'], [Sparkles, 'felix published cost-ceiling', 'New hook · #platform', '1d'], [Heart, 'erin followed zed-industries', 'New activity will appear in this feed', '1d'], [GitFork, 'dev merged upstream into oncall-loadout', '4 artifact updates · #support', '2d']]

function TeamActivity() {
  return <><TeamHero title="Activity" description="Announcements and changes across tootie.tv artifacts, projects, sessions, and people." action="New Announcement" icon={Activity} /><MockNotice />
    <div className="flex gap-5 border-b border-aurora-border-default/60" data-mock-region="team-activity-tabs">{[['Feed', '12'], ['Announcements', '3']].map(([tab, count], index) => <button key={tab} type="button" disabled className={`cursor-not-allowed border-b-2 px-1 py-2.5 text-[11.5px] font-semibold ${index === 0 ? 'border-aurora-accent-pink text-aurora-text-primary' : 'border-transparent text-aurora-text-muted'}`}>{tab}<span className="ml-1.5 rounded-full bg-aurora-control-surface px-1.5 py-0.5 text-[9px]">{count}</span></button>)}</div>
    <div className="grid gap-3 xl:grid-cols-[minmax(0,1fr)_300px]"><section className={CARD} data-mock-region="team-activity-feed"><SectionHeader icon={Radio} title="Your Feed" /><div className="flex gap-1.5 border-b border-aurora-border-default/50 px-4 py-3">{['All', 'Artifacts', 'Forks', 'Social'].map((filter, index) => <button key={filter} type="button" disabled className={`cursor-not-allowed rounded-full px-2.5 py-1 text-[10px] font-semibold ${index === 0 ? 'bg-aurora-accent-primary/12 text-aurora-accent-strong' : 'text-aurora-text-muted'}`}>{filter}</button>)}</div>{activityRows.map(([Icon, title, detail, time]) => <div key={title} className="flex gap-3 border-t border-aurora-border-default/45 px-4 py-3 first:border-t-0"><span className="grid size-8 shrink-0 place-items-center rounded-[9px] bg-aurora-control-surface"><Icon className="size-3.5 text-aurora-accent-pink" /></span><div className="min-w-0 flex-1"><div className="text-[11.5px] font-semibold text-aurora-text-primary">{title}</div><div className="mt-1 text-[10.5px] text-aurora-text-muted">{detail}</div></div><span className="shrink-0 text-[10px] text-aurora-text-muted">{time}</span></div>)}</section>
      <section className={`${CARD} h-fit`} data-mock-region="team-activity-suggestions"><SectionHeader icon={Sparkles} title="Suggested by Axon" />{[['secrets-sweeper', 'Agent'], ['doc-crawler', 'Skill'], ['zed-acp-bridge', 'Server'], ['pre-commit-guard', 'Hook']].map(([name, kind]) => <div key={name} className="flex items-center gap-3 border-t border-aurora-border-default/45 px-4 py-3 first:border-t-0"><span className="grid size-8 place-items-center rounded-[9px] bg-aurora-control-surface"><Globe2 className="size-3.5 text-aurora-accent-strong" /></span><div className="min-w-0 flex-1"><div className="truncate font-mono text-[10.5px] font-semibold text-aurora-text-primary">{name}</div><div className="mt-0.5 text-[9.5px] text-aurora-text-muted">{kind}</div></div><MockButton>Follow</MockButton></div>)}</section></div>
  </>
}

const stashRows = [['AGENTS.md', 'stash://team/AGENTS.md', 'J', 'jmagar', 'team', '24 KB'], ['incident-2026-08-14.md', 'stash://team/incident-2026-08-14.md', 'EW', 'erin walsh', 'team', '38 KB'], ['perf-baseline.json', 'stash://team/perf-baseline.json', 'CR', 'carla ruiz', 'agents', '780 KB'], ['container-manifest.toml', 'stash://team/container-manifest.toml', 'FN', 'felix nagy', 'team', '6 KB'], ['arch-diagram.png', 'stash://team/arch-diagram.png', 'AC', 'alice chen', 'public', '3.4 MB'], ['labby-0.24-release.tar.zst', 'stash://team/labby-0.24-release.tar.zst', 'J', 'jmagar', 'team', '188 MB'], ['scope-audit.csv', 'stash://team/scope-audit.csv', 'BO', 'ben okafor', 'agents', '96 KB']]

function TeamStash() {
  return <><TeamHero title="Stash" description="Shared files for tootie.tv people, agents, and projects. Address any file with a stable stash:// URI." action="Upload" icon={Archive} stats={[["Files", "7", "shared"], ["Size", "194 MB", "stored"], ["Agent Reads", "412", "this month"], ["Shared", "7", "files"], ["Workspace", "1", "team"]]} /><MockNotice />
    <section className={CARD} data-mock-region="team-stash-files"><SectionHeader icon={Archive} title="Files" meta="7 shared" /><div className="hidden grid-cols-[minmax(240px,1.5fr)_minmax(130px,1fr)_90px_75px_110px] gap-3 border-b border-aurora-border-default/45 px-4 py-2 text-[9px] font-bold uppercase tracking-[0.12em] text-aurora-text-muted md:grid"><span>Name</span><span>Owner</span><span>Access</span><span>Size</span><span className="text-right">Actions</span></div>{stashRows.map(([name, uri, initials, owner, access, size]) => <div key={name} className="grid gap-2 border-t border-aurora-border-default/40 px-4 py-3 first:border-t-0 md:grid-cols-[minmax(240px,1.5fr)_minmax(130px,1fr)_90px_75px_110px] md:items-center"><div className="flex min-w-0 items-center gap-3"><span className="grid size-8 shrink-0 place-items-center rounded-[9px] bg-aurora-control-surface"><FileCode2 className="size-3.5 text-aurora-accent-strong" /></span><div className="min-w-0"><div className="truncate font-mono text-[10.5px] font-semibold text-aurora-text-primary">{name}</div><div className="mt-0.5 truncate font-mono text-[9px] text-aurora-text-muted">{uri}</div></div></div><div className="flex items-center gap-2"><span className="grid size-6 place-items-center rounded-full bg-aurora-control-surface text-[7.5px] font-bold text-aurora-accent-strong">{initials}</span><span className="text-[10.5px] text-aurora-text-secondary">{owner}</span></div><span className="w-fit rounded-full border border-aurora-border-default/60 px-2 py-1 text-[9px] text-aurora-text-muted">{access}</span><span className="text-[10px] text-aurora-text-muted">{size}</span><div className="flex justify-end gap-1">{[[Copy, 'Copy'], [Share2, 'Share'], [MoreHorizontal, 'Remove']].map(([Icon, label]) => <button key={label as string} type="button" disabled title={`${label} unavailable — mock surface`} className="grid size-7 cursor-not-allowed place-items-center rounded-[7px] text-aurora-text-muted opacity-60"><Icon className="size-3.5" /></button>)}</div></div>)}</section>
  </>
}

const PAGE_META: Record<MockTeamPageKind, { title: string; label: string }> = { overview: { title: 'tootie.tv', label: 'Team Overview' }, library: { title: 'Team Library', label: 'Team Library' }, projects: { title: 'Projects', label: 'Projects' }, activity: { title: 'Activity', label: 'Activity' }, stash: { title: 'Stash', label: 'Team Stash' } }

const TEAM_PAGES: Record<MockTeamPageKind, ComponentType> = {
  overview: TeamOverview,
  library: TeamLibrary,
  projects: TeamProjects,
  activity: TeamActivity,
  stash: TeamStash,
}

export function MockTeamPage({ kind }: { kind: MockTeamPageKind }) {
  const meta = PAGE_META[kind]
  const Page = TEAM_PAGES[kind]
  const breadcrumbs = kind === 'overview' ? [{ label: 'Team' }] : [{ label: 'Team', href: '/team/' }, { label: meta.title }]
  return <><AppHeader breadcrumbs={breadcrumbs} /><section data-screen-label={meta.label} data-mock-surface="true" className="flex flex-col gap-[14px]"><Page /></section></>
}
