//! Action catalog for the `setup` Bootstrap orchestrator.

use labby_primitives::action::{ActionSpec, ParamSpec};

/// Setup actions that may only run from a trusted local transport. These
/// either mint first-run credentials or initiate an outbound connectivity
/// probe from the host, so an admin bearer alone is not sufficient.
pub const LOCAL_ONLY_ACTIONS: &[&str] = &["bootstrap", "proxy.configure"];

pub const ACTIONS: &[ActionSpec] = &[
    ActionSpec {
        name: "help",
        description: "Show this action catalog",
        destructive: false,
        requires_admin: false,
        returns: "Catalog",
        params: &[],
    },
    ActionSpec {
        name: "schema",
        description: "Return the parameter schema for a named action",
        destructive: false,
        requires_admin: false,
        returns: "Schema",
        params: &[ParamSpec {
            name: "action",
            ty: "string",
            required: true,
            description: "Action name to describe",
        }],
    },
    ActionSpec {
        name: "state",
        description: "First-run + draft snapshot for the wizard / settings UI",
        destructive: false,
        requires_admin: true,
        returns: "SetupSnapshot",
        params: &[],
    },
    ActionSpec {
        name: "bootstrap",
        description: "Create ~/.labby/.env with a generated token + loopback defaults when absent (first-run)",
        destructive: true,
        requires_admin: true,
        returns: "BootstrapOutcome",
        params: &[],
    },
    ActionSpec {
        name: "schema.get",
        description: "UiSchema projection for all (or filtered) services",
        destructive: false,
        requires_admin: false,
        returns: "ServiceSchemaMap",
        params: &[ParamSpec {
            name: "services",
            ty: "string[]",
            required: false,
            description: "Optional filter; defaults to every service in the registry",
        }],
    },
    ActionSpec {
        name: "draft.get",
        description: "Read .env.draft with secret values masked to '***'",
        destructive: false,
        requires_admin: true,
        returns: "DraftEntry[]",
        params: &[],
    },
    ActionSpec {
        name: "draft.set",
        description: "Write a key (or section) into .env.draft (validated server-side)",
        destructive: true,
        requires_admin: true,
        returns: "DraftSetOutcome",
        params: &[
            ParamSpec {
                name: "entries",
                ty: "DraftEntry[]",
                required: true,
                description: "Key/value pairs to write into the draft",
            },
            ParamSpec {
                name: "force",
                ty: "boolean",
                required: false,
                description: "Overwrite conflicting draft keys (default false)",
            },
        ],
    },
    ActionSpec {
        name: "draft.discard",
        description: "Discard .env.draft without modifying .env",
        destructive: true,
        requires_admin: true,
        returns: "DraftDiscardOutcome",
        params: &[],
    },
    ActionSpec {
        name: "draft.commit",
        description: "Run audit and atomically merge .env.draft into .env",
        destructive: true,
        requires_admin: true,
        returns: "CommitOutcome",
        params: &[ParamSpec {
            name: "force",
            ty: "boolean",
            required: false,
            description: "Overwrite conflicting .env keys (default false)",
        }],
    },
    ActionSpec {
        name: "settings.state",
        description: "Return section-scoped safe settings values and source metadata",
        destructive: false,
        requires_admin: true,
        returns: "SettingsState",
        params: &[ParamSpec {
            name: "section",
            ty: "string",
            required: false,
            description: "Settings section id; defaults to core",
        }],
    },
    ActionSpec {
        name: "settings.schema",
        description: "Return the safe settings schema with risk and write-policy metadata",
        destructive: false,
        requires_admin: false,
        returns: "SettingsSchema",
        params: &[],
    },
    ActionSpec {
        name: "settings.env_schema",
        description: "Return generated and registry-derived environment variable inventory",
        destructive: false,
        requires_admin: false,
        returns: "EnvSettingSpec[]",
        params: &[],
    },
    ActionSpec {
        name: "settings.advanced_state",
        description: "Return redacted advanced settings state",
        destructive: false,
        requires_admin: true,
        returns: "SettingsState",
        params: &[],
    },
    ActionSpec {
        name: "settings.update",
        description: "Update non-secret operator settings with validation",
        destructive: true,
        requires_admin: true,
        returns: "SettingsState",
        params: &[ParamSpec {
            name: "services.built_in_upstream_apis_enabled",
            ty: "boolean",
            required: true,
            description: "Enable built-in upstream API service integrations",
        }],
    },
    ActionSpec {
        name: "settings.config.update",
        description: "Admin-only scalar config.toml settings update",
        destructive: true,
        requires_admin: true,
        returns: "SettingsMutationOutcome",
        params: &[ParamSpec {
            name: "entries",
            ty: "SettingsUpdateEntry[]",
            required: true,
            description: "Schema-approved config scalar updates",
        }],
    },
    ActionSpec {
        name: "settings.env.update",
        description: "Admin-only targeted .env settings update for known low-risk LABBY_* keys",
        destructive: true,
        requires_admin: true,
        returns: "SettingsState",
        params: &[ParamSpec {
            name: "entries",
            ty: "SettingsUpdateEntry[]",
            required: true,
            description: "Schema-approved env scalar updates",
        }],
    },
    ActionSpec {
        name: "check",
        description: "Check local Lab setup prerequisites without mutating the filesystem",
        destructive: false,
        requires_admin: false,
        returns: "SetupReport",
        params: &[],
    },
    ActionSpec {
        name: "repair",
        description: "Repair missing local Lab setup prerequisites without contacting external services",
        destructive: true,
        requires_admin: true,
        returns: "SetupReport",
        params: &[],
    },
    ActionSpec {
        name: "proxy.configure",
        description: "Persist local stdio-proxy defaults and securely store a bearer secret when required",
        destructive: true,
        requires_admin: true,
        returns: "ProxySetupOutcome",
        params: &[
            ParamSpec {
                name: "preferences",
                ty: "ProxyPreferences",
                required: true,
                description: "Validated non-secret proxy preferences to persist in config.toml",
            },
            ParamSpec {
                name: "bearer_token",
                ty: "string",
                required: false,
                description: "Write-only bearer token read from stdin; never returned or logged",
            },
            ParamSpec {
                name: "dry_run",
                ty: "boolean",
                required: false,
                description: "Preview whether config or secret files would change without mutation",
            },
        ],
    },
    ActionSpec {
        name: "finalize",
        description: "Alias for draft.commit; same params, same returns",
        destructive: true,
        requires_admin: true,
        returns: "CommitOutcome",
        params: &[ParamSpec {
            name: "force",
            ty: "boolean",
            required: false,
            description: "Overwrite conflicting .env keys (default false)",
        }],
    },
];
