//! Readiness receipts derive only from host-established identity and qualified search.
use super::*;
use crate::dispatch::setup::readiness::{self, Check};

pub(super) struct CatalogCheck {
    store: crate::access::AccessStore,
    principal: String,
    fingerprint: readiness::CheckFingerprint,
}
impl CatalogCheck {
    pub(super) async fn begin(
        state: &AppState,
        identity: Option<&VerifiedIdentity>,
    ) -> Result<Option<Self>, (StatusCode, Json<Value>)> {
        let Some(identity) = identity else {
            return Ok(None);
        };
        let store = state
            .access_runtime
            .store()
            .await
            .map_err(|_| unavailable())?;
        let principal = store
            .resolve_file_stash_principal(identity.clone())
            .await
            .map_err(|_| forbidden())?
            .as_str()
            .to_owned();
        let capture_store = store.clone();
        let subject = principal.clone();
        let fingerprint = tokio::task::spawn_blocking(move || {
            readiness::begin_verification_for_store(&capture_store, &subject, Check::CatalogSearch)
        })
        .await
        .map_err(|_| unavailable())?
        .map_err(|_| unavailable())?;
        Ok(Some(Self {
            store,
            principal,
            fingerprint,
        }))
    }
    pub(super) async fn fail(self) -> Result<(), (StatusCode, Json<Value>)> {
        tokio::task::spawn_blocking(move || {
            readiness::fail_verification_for_store(&self.store, &self.principal, self.fingerprint)
        })
        .await
        .map_err(|_| unavailable())?
        .map_err(|_| unavailable())
    }
    pub(super) async fn finish(self, response: &Value) -> Result<(), (StatusCode, Json<Value>)> {
        let Some(provider) = qualified_provider(response) else {
            if healthy_empty_search(response) {
                tokio::task::spawn_blocking(move || {
                    readiness::preserve_catalog_verification_for_store(
                        &self.store,
                        &self.principal,
                        self.fingerprint,
                    )
                })
                .await
                .map_err(|_| unavailable())?
                .map_err(|_| unavailable())?;
            } else {
                self.fail().await?;
            }
            return Ok(());
        };
        tokio::task::spawn_blocking(move || {
            readiness::record_verified_if_unchanged_for_store(
                &self.store,
                &self.principal,
                Check::CatalogSearch,
                &provider,
                self.fingerprint,
            )
        })
        .await
        .map_err(|_| unavailable())?
        .map_err(|_| unavailable())
    }
}
fn unavailable() -> (StatusCode, Json<Value>) {
    (
        StatusCode::SERVICE_UNAVAILABLE,
        Json(
            json!({"error":"catalog_readiness_unavailable","message":"Catalog verification could not be recorded. Retry the search."}),
        ),
    )
}
// discover_with_access_epoch qualifies provider identity before fetching its first
// page; participating is generated by that runtime, never by browser request data.
fn healthy_empty_search(response: &Value) -> bool {
    response.get("state").and_then(Value::as_str) == Some("empty")
        && response.get("coverageComplete").and_then(Value::as_bool) == Some(true)
        && response
            .get("failures")
            .and_then(Value::as_array)
            .is_some_and(Vec::is_empty)
        && response
            .get("items")
            .and_then(Value::as_array)
            .is_some_and(Vec::is_empty)
        && response
            .get("providerOutcomes")
            .and_then(Value::as_array)
            .is_some_and(|outcomes| {
                outcomes.iter().any(|outcome| {
                    matches!(
                        outcome.get("state").and_then(Value::as_str),
                        Some("participating" | "exhausted")
                    )
                })
            })
}

fn qualified_provider(response: &Value) -> Option<String> {
    if response.get("state")?.as_str()? != "complete"
        || !response.get("coverageComplete")?.as_bool()?
        || !response.get("failures")?.as_array()?.is_empty()
        || response.get("items")?.as_array()?.is_empty()
    {
        return None;
    }
    let provider = response
        .get("providerOutcomes")?
        .as_array()?
        .iter()
        .find(|outcome| outcome.get("state").and_then(Value::as_str) == Some("participating"))?
        .get("providerId")?
        .as_str()?;
    (!provider.is_empty() && provider.len() <= 256).then(|| provider.to_owned())
}
#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    #[allow(clippy::disallowed_methods)]
    fn empty_search_is_healthy_only_with_qualified_complete_provider_coverage() {
        let healthy = json!({"state":"empty","coverageComplete":true,"items":[],"failures":[],"providerOutcomes":[{"providerId":"public","state":"participating"}]});
        assert!(healthy_empty_search(&healthy));
        for patch in [
            json!({"coverageComplete":false}),
            json!({"failures":[{"kind":"forbidden"}]}),
            json!({"providerOutcomes":[]}),
            json!({"state":"all_failed"}),
        ] {
            let mut response = healthy.clone();
            response
                .as_object_mut()
                .unwrap()
                .extend(patch.as_object().unwrap().clone());
            assert!(!healthy_empty_search(&response));
        }
    }
    #[test]
    #[allow(clippy::disallowed_methods)]
    fn only_complete_qualified_real_results_earn_catalog_evidence() {
        let complete = json!({"state":"complete","coverageComplete":true,"items":[{"artifactId":"real"}],"failures":[],"providerOutcomes":[{"providerId":"public","state":"participating"}]});
        assert_eq!(qualified_provider(&complete).as_deref(), Some("public"));
        for patch in [
            json!({"items":[]}),
            json!({"state":"empty"}),
            json!({"state":"all_failed","failures":[{"kind":"index_not_ready"}]}),
            json!({"failures":[{"kind":"forbidden"}]}),
            json!({"coverageComplete":false}),
            json!({"providerOutcomes":[{"providerId":"public","state":"pending"}]}),
        ] {
            let mut response = complete.clone();
            response
                .as_object_mut()
                .unwrap()
                .extend(patch.as_object().unwrap().clone());
            assert_eq!(qualified_provider(&response), None);
        }
    }
}
