use labby_primitives::product_credential::BoundAccessGrant;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct AuthorizationServerMetadata {
    pub issuer: String,
    pub authorization_endpoint: String,
    pub token_endpoint: String,
    pub revocation_endpoint: String,
    pub registration_endpoint: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub native_callback_endpoint: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub native_poll_endpoint: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub native_poll_endpoint_v2: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub native_authorization_start_media_type: Option<String>,
    pub jwks_uri: String,
    pub response_types_supported: Vec<String>,
    pub scopes_supported: Vec<String>,
    pub grant_types_supported: Vec<String>,
    pub code_challenge_methods_supported: Vec<String>,
    pub token_endpoint_auth_methods_supported: Vec<String>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub token_endpoint_auth_signing_alg_values_supported: Vec<String>,
    pub authorization_response_iss_parameter_supported: bool,
    pub client_id_metadata_document_supported: bool,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub authorization_grant_profiles_supported: Vec<String>,
}

/// Query params for the direct-hit native callback fallback.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct NativeCallbackQuery {
    pub state: String,
}

/// Secret-bearing JSON body for `POST /native/poll`. The token is generated by the
/// authorization server and is independent of the caller-provided OAuth
/// `state`, which remains CSRF/callback correlation only.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct NativePollQuery {
    pub poll_token: String,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct NativeAuthorizationStartResponse {
    pub authorization_url: String,
    pub poll_token: String,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct NativePollResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
}

/// A native-flow authorization code, stored server-side keyed by a hash of an
/// independent server-generated polling token
/// until the polling client retrieves it (`take_native_authorization_result`
/// is a one-shot read-and-delete).
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct NativeAuthorizationResultRow {
    pub poll_token_hash: String,
    pub code: String,
    pub created_at: i64,
    pub expires_at: i64,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ProtectedResourceMetadata {
    pub resource: String,
    pub authorization_servers: Vec<String>,
    pub scopes_supported: Vec<String>,
    pub bearer_methods_supported: Vec<String>,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ClientRegistrationRequest {
    pub redirect_uris: Vec<String>,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ClientRegistrationResponse {
    pub client_id: String,
    pub redirect_uris: Vec<String>,
    pub token_endpoint_auth_method: String,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct AuthorizeQuery {
    #[serde(default)]
    pub response_type: String,
    pub client_id: String,
    pub redirect_uri: String,
    pub state: String,
    #[serde(default)]
    pub resource: Option<String>,
    #[serde(default)]
    pub scope: String,
    pub code_challenge: String,
    pub code_challenge_method: String,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct CallbackQuery {
    pub state: String,
    pub code: String,
}

#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct BrowserLoginQuery {
    #[serde(default)]
    pub return_to: Option<String>,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct TokenRequest {
    pub grant_type: String,
    #[serde(default)]
    pub code: Option<String>,
    #[serde(default)]
    pub client_id: Option<String>,
    #[serde(default)]
    pub resource: Option<String>,
    #[serde(default)]
    pub redirect_uri: Option<String>,
    #[serde(default)]
    pub code_verifier: Option<String>,
    #[serde(default)]
    pub refresh_token: Option<String>,
    #[serde(default)]
    pub scope: Option<String>,
    #[serde(default)]
    pub client_secret: Option<String>,
    #[serde(default)]
    pub client_assertion_type: Option<String>,
    #[serde(default)]
    pub client_assertion: Option<String>,
    #[serde(default)]
    pub assertion: Option<String>,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct RevocationRequest {
    pub token: String,
    #[serde(default)]
    pub token_type_hint: Option<String>,
    #[serde(default)]
    pub client_id: Option<String>,
    #[serde(default)]
    pub client_secret: Option<String>,
    #[serde(default)]
    pub client_assertion_type: Option<String>,
    #[serde(default)]
    pub client_assertion: Option<String>,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct TokenResponse {
    pub access_token: String,
    pub token_type: String,
    pub expires_in: u64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub refresh_token: Option<String>,
    pub scope: String,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct RegisteredClient {
    pub client_id: String,
    pub redirect_uris: Vec<String>,
    pub created_at: i64,
    /// The client's *preferred* token-endpoint authentication method.
    #[serde(default = "default_token_endpoint_auth_method")]
    pub token_endpoint_auth_method: String,
    /// Every method this client may authenticate with, preference first.
    ///
    /// Populated from a CIMD document's `token_endpoint_auth_methods_supported`
    /// unioned with its `token_endpoint_auth_method`. Empty means "fall back to
    /// `token_endpoint_auth_method`" — which is what every non-CIMD row does,
    /// since the SQLite store does not persist either field.
    #[serde(default)]
    pub token_endpoint_auth_methods: Vec<String>,
    #[serde(default)]
    pub jwks: Option<serde_json::Value>,
    /// HTTPS location of the client's public key set, used when the client
    /// publishes `jwks_uri` instead of an inline `jwks`. Only ever populated
    /// from a Client ID Metadata Document, and only after the URL passes the
    /// shared SSRF preflight.
    #[serde(default)]
    pub jwks_uri: Option<String>,
}

fn default_token_endpoint_auth_method() -> String {
    "none".to_string()
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct AuthorizationRequestRow {
    pub state: String,
    pub client_id: String,
    pub redirect_uri: String,
    pub client_state: String,
    #[serde(default)]
    pub native_poll_token_hash: Option<String>,
    pub resource: String,
    pub scope: String,
    pub provider_code_verifier: String,
    pub code_challenge: String,
    pub code_challenge_method: String,
    pub created_at: i64,
    pub expires_at: i64,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct AuthorizationCodeRow {
    pub code: String,
    pub client_id: String,
    pub subject: String,
    pub redirect_uri: String,
    pub resource: String,
    pub scope: String,
    pub code_challenge: String,
    pub code_challenge_method: String,
    pub provider_refresh_token: Option<String>,
    pub created_at: i64,
    pub expires_at: i64,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct RefreshTokenRow {
    pub refresh_token: String,
    pub client_id: String,
    pub subject: String,
    pub resource: String,
    pub scope: String,
    pub provider_refresh_token: Option<String>,
    pub created_at: i64,
    pub expires_at: i64,
}

/// The single reusable Google refresh credential for a verified provider subject.
///
/// The refresh token is encrypted at rest by [`SqliteStore`](crate::sqlite::SqliteStore).
/// `generation` increments whenever the credential is replaced so an in-flight
/// invalidation cannot delete a newer credential installed by another request.
///
/// `Debug` is implemented manually with redaction — never derive it.
#[derive(Clone, PartialEq, Eq)]
pub struct GoogleProviderCredentialRow {
    pub subject: String,
    pub email: Option<String>,
    pub client_id: String,
    pub granted_scopes: Vec<String>,
    pub access_token: Option<String>,
    pub refresh_token: String,
    pub token_received_at: Option<i64>,
    pub access_token_expires_at: Option<i64>,
    pub issuer: Option<String>,
    pub last_refresh_at: Option<i64>,
    pub last_scope_upgrade_at: Option<i64>,
    pub generation: i64,
    pub created_at: i64,
    pub updated_at: i64,
}

impl std::fmt::Debug for GoogleProviderCredentialRow {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("GoogleProviderCredentialRow")
            .field("subject", &"<redacted>")
            .field("email", &self.email.as_ref().map(|_| "<redacted>"))
            .field("client_id", &self.client_id)
            .field("granted_scopes", &self.granted_scopes)
            .field(
                "access_token",
                &self.access_token.as_ref().map(|_| "<redacted>"),
            )
            .field("refresh_token", &"<redacted>")
            .field("token_received_at", &self.token_received_at)
            .field("access_token_expires_at", &self.access_token_expires_at)
            .field("issuer", &self.issuer)
            .field("last_refresh_at", &self.last_refresh_at)
            .field("last_scope_upgrade_at", &self.last_scope_upgrade_at)
            .field("generation", &self.generation)
            .field("created_at", &self.created_at)
            .field("updated_at", &self.updated_at)
            .finish()
    }
}

/// Full token-bundle update for the central Google credential broker.
///
/// The refresh and access tokens are encrypted by `SqliteStore`; this value must
/// never be logged or included in API responses.
#[derive(Clone)]
pub struct GoogleProviderCredentialUpdate {
    pub subject: String,
    pub email: Option<String>,
    pub client_id: String,
    pub granted_scopes: Vec<String>,
    pub access_token: String,
    pub refresh_token: String,
    pub token_received_at: i64,
    pub access_token_expires_at: i64,
    pub issuer: Option<String>,
    pub refreshed: bool,
    pub scope_upgraded: bool,
}

impl std::fmt::Debug for GoogleProviderCredentialUpdate {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("GoogleProviderCredentialUpdate")
            .field("subject", &"<redacted>")
            .field("email", &self.email.as_ref().map(|_| "<redacted>"))
            .field("client_id", &self.client_id)
            .field("granted_scopes", &self.granted_scopes)
            .field("access_token", &"<redacted>")
            .field("refresh_token", &"<redacted>")
            .field("token_received_at", &self.token_received_at)
            .field("access_token_expires_at", &self.access_token_expires_at)
            .field("issuer", &self.issuer)
            .field("refreshed", &self.refreshed)
            .field("scope_upgraded", &self.scope_upgraded)
            .finish()
    }
}

#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct GoogleProviderInvalidation {
    pub invalidated: bool,
    pub revoked_refresh_tokens: u64,
    pub revoked_authorization_codes: u64,
}

#[derive(Clone, Default, PartialEq, Eq)]
pub struct AllowedUserRevocation {
    pub subjects: Vec<String>,
    pub revoked_sessions: u64,
    pub revoked_provider_credentials: u64,
    pub revoked_refresh_tokens: u64,
    pub revoked_authorization_codes: u64,
}

impl std::fmt::Debug for AllowedUserRevocation {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter
            .debug_struct("AllowedUserRevocation")
            .field("subject_count", &self.subjects.len())
            .field("subjects", &"<redacted>")
            .field("revoked_sessions", &self.revoked_sessions)
            .field(
                "revoked_provider_credentials",
                &self.revoked_provider_credentials,
            )
            .field("revoked_refresh_tokens", &self.revoked_refresh_tokens)
            .field(
                "revoked_authorization_codes",
                &self.revoked_authorization_codes,
            )
            .finish()
    }
}

/// Immutable authorization facts captured when a project browser session is
/// created.  The credential secret is deliberately absent; only its stable ID
/// and generation are persisted.
#[derive(Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ProjectSessionBinding {
    pub installation_id: String,
    pub issuer: String,
    pub subject: String,
    pub principal_id: String,
    pub organization_id: String,
    pub project_id: String,
    pub loadout_id: String,
    pub loadout_generation: u64,
    pub assignment_generation: u64,
    pub catalog_generation: u64,
    pub route_id: String,
    pub route_generation: u64,
    pub membership_epoch: u64,
    pub organization_policy_epoch: u64,
    pub project_policy_epoch: u64,
    pub source_credential_id: String,
    pub source_credential_generation: u64,
    pub scopes: Vec<String>,
    pub resource: String,
    pub audience: String,
    pub source_credential_expires_at: u64,
}

impl From<&BoundAccessGrant> for ProjectSessionBinding {
    fn from(grant: &BoundAccessGrant) -> Self {
        Self {
            installation_id: grant.installation_id.clone(),
            issuer: grant.issuer.clone(),
            subject: grant.subject.clone(),
            principal_id: grant.principal_id.clone(),
            organization_id: grant.organization_id.clone(),
            project_id: grant.project_id.clone(),
            loadout_id: grant.loadout_id.clone(),
            loadout_generation: grant.loadout_generation,
            assignment_generation: grant.assignment_generation,
            catalog_generation: grant.catalog_generation,
            route_id: grant.route_id.clone(),
            route_generation: grant.route_generation,
            membership_epoch: grant.membership_epoch,
            organization_policy_epoch: grant.organization_policy_epoch,
            project_policy_epoch: grant.project_policy_epoch,
            source_credential_id: grant.credential_id.clone(),
            source_credential_generation: grant.credential_generation,
            scopes: grant.scopes.clone(),
            resource: grant.resource.clone(),
            audience: grant.audience.clone(),
            source_credential_expires_at: grant.expires_at,
        }
    }
}

#[derive(Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct BrowserSessionRow {
    pub session_id: String,
    pub subject: String,
    pub email: Option<String>,
    pub csrf_token: String,
    pub created_at: i64,
    pub expires_at: i64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub project_binding: Option<ProjectSessionBinding>,
}

impl std::fmt::Debug for BrowserSessionRow {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter
            .debug_struct("BrowserSessionRow")
            .field("session_id", &"<redacted>")
            .field("subject", &"<redacted>")
            .field("email_present", &self.email.is_some())
            .field("csrf_token", &"<redacted>")
            .field("created_at", &self.created_at)
            .field("expires_at", &self.expires_at)
            .field("project_bound", &self.project_binding.is_some())
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct BrowserLoginStateRow {
    pub state: String,
    pub return_to: String,
    pub provider_code_verifier: String,
    pub created_at: i64,
    pub expires_at: i64,
}

/// Persisted upstream OAuth credential row.
///
/// The encrypted `token_blob` is `chacha20poly1305(token_response_json)` sealed with a
/// fresh 12-byte nonce per write. `access_token_expires_at` is denormalized for cheap
/// pruning in `cleanup_expired`. `refresh_token_present` enables dropping access-only
/// stale rows while keeping rows that still have a refresh token for re-use (SEC-9).
///
/// `Debug` is implemented manually with redaction — never derive it.
#[derive(Clone)]
pub struct UpstreamOauthCredentialRow {
    pub upstream_name: String,
    pub subject: String,
    pub client_id: String,
    pub granted_scopes_json: String,
    pub token_blob: Vec<u8>,
    pub token_blob_nonce: Vec<u8>,
    pub token_received_at: i64,
    pub access_token_expires_at: i64,
    pub refresh_token_present: bool,
}

impl std::fmt::Debug for UpstreamOauthCredentialRow {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("UpstreamOauthCredentialRow")
            .field("upstream_name", &self.upstream_name)
            .field("subject", &"<redacted>")
            .field("client_id", &self.client_id)
            .field("granted_scopes_json", &self.granted_scopes_json)
            .field("token_blob", &"<redacted>")
            .field("token_blob_nonce", &"<redacted>")
            .field("token_received_at", &self.token_received_at)
            .field("access_token_expires_at", &self.access_token_expires_at)
            .field("refresh_token_present", &self.refresh_token_present)
            .finish()
    }
}

/// Short-lived upstream OAuth state row. Holds the CSRF token and PKCE verifier
/// between `/authorize` redirect and `/callback` redemption.
///
/// `expires_at - created_at` MUST NOT exceed 600 seconds. The persistence helper
/// rejects violations.
///
/// `Debug` is implemented manually with redaction — never derive it (`pkce_verifier`
/// is sensitive).
#[derive(Clone)]
pub struct UpstreamOauthStateRow {
    pub upstream_name: String,
    pub subject: String,
    pub csrf_token: String,
    pub pkce_verifier: String,
    pub created_at: i64,
    pub expires_at: i64,
}

/// A row from the `allowed_users` table.
///
/// Email is always stored and returned in lowercase. `added_by` is the subject
/// of the admin who added the entry. Never log `email` directly — use
/// `util::fingerprint(email)` for safe diagnostic output.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct AllowedUserRow {
    pub email: String,
    pub added_by: String,
    pub created_at: i64,
}

impl std::fmt::Debug for UpstreamOauthStateRow {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("UpstreamOauthStateRow")
            .field("upstream_name", &self.upstream_name)
            .field("subject", &"<redacted>")
            .field("csrf_token", &"<redacted>")
            .field("pkce_verifier", &"<redacted>")
            .field("created_at", &self.created_at)
            .field("expires_at", &self.expires_at)
            .finish()
    }
}
