use labby_primitives::action::{ActionSpec, ParamSpec};

pub const ACTIONS: &[ActionSpec] = &[
    ActionSpec {
        name: "help",
        description: "Show this action catalog",
        destructive: false,
        requires_admin: false,
        returns: "Catalog",
        output_schema: None,
        params: &[],
    },
    ActionSpec {
        name: "schema",
        description: "Return the parameter schema for a named action",
        destructive: false,
        requires_admin: false,
        returns: "Schema",
        output_schema: None,
        params: &[ParamSpec {
            name: "action",
            ty: "string",
            required: true,
            description: "Action name to describe",
        }],
    },
    ActionSpec {
        name: "snippets.list",
        description: "List built-in and user executable Code Mode snippets",
        destructive: false,
        requires_admin: false,
        returns: "SnippetList",
        output_schema: None,
        params: &[],
    },
    ActionSpec {
        name: "snippets.get",
        description: "Return one snippet body and metadata",
        destructive: false,
        requires_admin: true,
        returns: "ResolvedSnippet",
        output_schema: None,
        params: &[ParamSpec {
            name: "name",
            ty: "string",
            required: true,
            description: "Snippet name",
        }],
    },
    ActionSpec {
        name: "snippets.exec",
        description: "Execute a snippet through gateway Code Mode",
        destructive: false,
        requires_admin: true,
        returns: "CodeModeExecutionResponse",
        output_schema: None,
        params: &[
            ParamSpec {
                name: "name",
                ty: "string",
                required: true,
                description: "Snippet name",
            },
            ParamSpec {
                name: "params",
                ty: "object",
                required: false,
                description: "Input object passed to the snippet async function",
            },
        ],
    },
    ActionSpec {
        name: "snippets.create",
        description: "Create a user snippet under LABBY_HOME/snippets",
        destructive: false,
        requires_admin: true,
        returns: "SnippetInfo",
        output_schema: None,
        params: &[
            ParamSpec {
                name: "name",
                ty: "string",
                required: true,
                description: "Snippet name",
            },
            ParamSpec {
                name: "body",
                ty: "string",
                required: true,
                description: "Markdown or JavaScript snippet body",
            },
            ParamSpec {
                name: "description",
                ty: "string",
                required: false,
                description: "Description written to generated frontmatter",
            },
            ParamSpec {
                name: "force",
                ty: "boolean",
                required: false,
                description: "Overwrite an existing user snippet",
            },
        ],
    },
    ActionSpec {
        name: "snippets.promote",
        description: "Promote a successful live Code Mode execution into a user snippet",
        destructive: true,
        requires_admin: true,
        returns: "SnippetPromotionResult",
        output_schema: None,
        params: &[
            ParamSpec {
                name: "execution_id",
                ty: "string",
                required: true,
                description: "Live gateway Code Mode execution id",
            },
            ParamSpec {
                name: "name",
                ty: "string",
                required: true,
                description: "Target user snippet name",
            },
            ParamSpec {
                name: "description",
                ty: "string",
                required: false,
                description: "Snippet description",
            },
            ParamSpec {
                name: "force",
                ty: "boolean",
                required: false,
                description: "Overwrite an existing user snippet",
            },
            ParamSpec {
                name: "shadow_builtin",
                ty: "boolean",
                required: false,
                description: "Allow creating a user snippet that shadows a built-in snippet",
            },
        ],
    },
    ActionSpec {
        name: "snippets.validate",
        description: "Validate a snippet body or existing snippet without executing it",
        destructive: false,
        requires_admin: true,
        returns: "SnippetValidation",
        output_schema: None,
        params: &[
            ParamSpec {
                name: "name",
                ty: "string",
                required: false,
                description: "Snippet name or filename stem",
            },
            ParamSpec {
                name: "body",
                ty: "string",
                required: false,
                description: "Markdown or JavaScript snippet body to validate",
            },
        ],
    },
    ActionSpec {
        name: "snippets.remove",
        description: "Remove a user snippet",
        destructive: true,
        requires_admin: true,
        returns: "SnippetRemoveResult",
        output_schema: None,
        params: &[ParamSpec {
            name: "name",
            ty: "string",
            required: true,
            description: "User snippet name",
        }],
    },
    ActionSpec {
        name: "snippets.test",
        description: "Execute one snippet and report pass/fail",
        destructive: false,
        requires_admin: true,
        returns: "SnippetTestResult",
        output_schema: None,
        params: &[
            ParamSpec {
                name: "name",
                ty: "string",
                required: false,
                description: "Snippet name",
            },
            ParamSpec {
                name: "params",
                ty: "object",
                required: false,
                description: "Input object passed to the snippet async function",
            },
            ParamSpec {
                name: "all",
                ty: "boolean",
                required: false,
                description: "Run every listed snippet with default params",
            },
        ],
    },
];
