name: Pull request labels

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    uses: dinglebear-ai/workflows/.github/workflows/repository-labeler.yml@eb5f36cf517ffc949aca1c81e2ccbc71b5a85267
    with:
      configuration-path: .github/labeler.yml
      sync-labels: true
